# Generated by Django 3.2.9 on 2021-12-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zikime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.ForeignKey(db_column='Serial_ID', help_text='This value is automatically entered by reference.', on_delete=django.db.models.deletion.CASCADE, related_name='serial', to='zikime.serial', verbose_name='시리얼 번호'),
        ),
    ]
