# Generated by Django 3.2.9 on 2022-01-06 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zikime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '게스트',
                'verbose_name_plural': '게스트 리스트',
                'db_table': 'Guest',
            },
        ),
        migrations.RemoveField(
            model_name='regist',
            name='device',
        ),
        migrations.RemoveField(
            model_name='regist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='status',
            name='device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='camera_module_info',
        ),
        migrations.RemoveField(
            model_name='device',
            name='gps_module_info',
        ),
        migrations.AddField(
            model_name='device',
            name='master',
            field=models.ForeignKey(db_column='Master', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='zikime.customuser', verbose_name='마스터'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CRE_DT', help_text='This value is automatically entered when the table is created.', null=True, verbose_name='생성 날짜'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(db_column='Serial_ID', help_text='This value is automatically entered by reference.', max_length=100, verbose_name='시리얼 번호'),
        ),
        migrations.AlterModelTable(
            name='device',
            table='Device',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Regist',
        ),
        migrations.DeleteModel(
            name='Serial',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='guest',
            name='device',
            field=models.ForeignKey(db_column='Device', on_delete=django.db.models.deletion.CASCADE, related_name='device', to='zikime.device', verbose_name='디바이스 id'),
        ),
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='유저 id'),
        ),
    ]
