# Generated by Django 3.2.9 on 2022-01-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zikime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='CITY_NAME', max_length=20)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country_CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='COUNTRY_NAME', max_length=20)),
                ('city', models.ForeignKey(db_column='CITY', on_delete=django.db.models.deletion.CASCADE, to='zikime.city_csv')),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='District_CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='DISTRICT_NAME', max_length=20)),
                ('country', models.ForeignKey(db_column='COUNTRY', on_delete=django.db.models.deletion.CASCADE, to='zikime.country_csv')),
            ],
            options={
                'db_table': 'District',
            },
        ),
    ]
