# Generated by Django 3.2.9 on 2022-01-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zikime', '0002_city_csv_country_csv_district_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_csv',
            name='city',
            field=models.ForeignKey(db_column='CITY', default='city', on_delete=django.db.models.deletion.CASCADE, to='zikime.city_csv'),
        ),
        migrations.AlterField(
            model_name='district_csv',
            name='country',
            field=models.ForeignKey(db_column='COUNTRY', default='country', on_delete=django.db.models.deletion.CASCADE, to='zikime.country_csv'),
        ),
    ]
