# Generated by Django 3.2.9 on 2021-12-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikime', '0002_alter_device_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='serial_number',
            field=models.IntegerField(db_column='SerialID', help_text='This serial number must be unique.', max_length=50, verbose_name='시리얼 번호'),
        ),
    ]
