# Generated by Django 3.2.9 on 2021-12-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikime', '0003_alter_serial_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='serial_number',
            field=models.CharField(db_column='SerialID', help_text='This serial number must be unique.', max_length=50, unique=True, verbose_name='시리얼 번호'),
        ),
    ]
