# Generated by Django 3.2.9 on 2022-01-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zikime', '0003_auto_20220115_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city_csv',
            options={'verbose_name': '시', 'verbose_name_plural': '시 리스트'},
        ),
        migrations.AlterModelOptions(
            name='country_csv',
            options={'verbose_name': '구', 'verbose_name_plural': '구 리스트'},
        ),
        migrations.AlterModelOptions(
            name='district_csv',
            options={'verbose_name': '동', 'verbose_name_plural': '동 리스트'},
        ),
        migrations.CreateModel(
            name='DistrictWhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(db_column='Device', on_delete=django.db.models.deletion.CASCADE, related_name='white_list_device', to='zikime.device', verbose_name='디바이스')),
                ('white_list', models.ForeignKey(db_column='WhiteList', on_delete=django.db.models.deletion.CASCADE, related_name='list', to='zikime.district_csv', verbose_name='안심지역')),
            ],
            options={
                'verbose_name': '안심지역',
                'verbose_name_plural': '안심지역 리스트',
                'db_table': 'DistrictWhiteList',
            },
        ),
    ]
